export const GET_WEATHER_CITY = "GET_WEATHER_CITY";
export const DELETE_WEATHER_CITY = "DELETE_WEATHER_CITY";
export const UPDATE_WEATHER_CITY = "UPDATE_WEATHER_CITY";
export const GET_COUNTRIES_LIST = "GET_COUNTRIES_LIST";
